version: 2

# try adding a Redshift table as a source!
sources:
  - name: redshift
    schema: <your_redshift_schema>
    catalog: <your_redshift_catalog> 
    config:
      enabled: false
    tables:
      - name: <your_redshift_table>
